completed prep css flexbox exercise - Dana Rayan
Danarayan/prep-0422-code-solutions pull request #8
Opened 2022-04-23 20:48 UTC by Danarayan

![Screen Shot 2022-04-23 at 1 42 00 PM](https://user-images.githubusercontent.com/103712307/164945496-a2a80129-45f2-4c2c-93ae-618d09355014.png)
![Screen Shot 2022-04-23 at 1 42 25 PM](https://user-images.githubusercontent.com/103712307/164945497-a13c6cfb-1561-4fe8-9704-86e757227b28.png)
![Screen Shot 2022-04-23 at 1 43 07 PM](https://user-images.githubusercontent.com/103712307/164945498-3e461d13-3ade-424a-b860-e19b864afa79.png)
![Screen Shot 2022-04-23 at 1 43 21 PM](https://user-images.githubusercontent.com/103712307/164945499-5c3bd506-78f1-4499-84f4-eef128b1d114.png)

2022-04-23 21:19 UTC, thebearingedge requested changes

2022-04-23 21:19 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      min-height: 100vh;
Hi Dana, for all of your files here, be sure to put `flex-basis` on the `.card-wrapper`. 

`flex-basis` is meant to be used on the children of elements with `display: flex`

2022-04-27 19:30 UTC, Danarayan commented
Hey, Tim!
I went through all of the files in the flexbox exercise and corrected the .card-wrapper by adding or moving flex-basis to it,  because they are child elements of the element that contain display: flex; 💯 

![Screen Shot 2022-04-27 at 12 21 40 PM](https://user-images.githubusercontent.com/103712307/165604897-77ede909-148f-4a9d-86e5-cee99e441e8f.png)

![Screen Shot 2022-04-27 at 12 19 55 PM](https://user-images.githubusercontent.com/103712307/165604880-970e27a6-8b58-4f00-8db7-3295448e23d5.png)

![Screen Shot 2022-04-27 at 12 20 29 PM](https://user-images.githubusercontent.com/103712307/165604889-4da9f127-9440-465a-891a-094222e3a944.png)

![Screen Shot 2022-04-27 at 12 21 14 PM](https://user-images.githubusercontent.com/103712307/165604893-8717cca9-cb0a-4bc2-affc-fdf3c366c0e7.png)

2022-04-27 19:59 UTC, thebearingedge approved these changes

2022-04-27 20:10 UTC, merged